Fix CI failure TypeError: _window.mainWindow.matchMedia is not a function (#2343)
* Fix CI by extracting EuInMemoryTable searchConfig to variable

Signed-off-by: Craig Perkins <cwperx@amazon.com>

* Modify public/test/plugin.test.ts

Signed-off-by: Craig Perkins <cwperx@amazon.com>

* Revert "Fix CI by extracting EuInMemoryTable searchConfig to variable"

This reverts commit aebe45a5d468312da2cfebe4fd42ec43f77f71cf.

Signed-off-by: Craig Perkins <cwperx@amazon.com>

* Use ci.opensearch

Signed-off-by: Craig Perkins <cwperx@amazon.com>

* Adapt to name change

Signed-off-by: Craig Perkins <cwperx@amazon.com>

* Fix unit tests

Signed-off-by: Craig Perkins <cwperx@amazon.com>

* Fix unit tests

Signed-off-by: Craig Perkins <cwperx@amazon.com>

---------

Signed-off-by: Craig Perkins <cwperx@amazon.com>